Add tests
AY2223S1-CS2103T-T10-1/tp pull request #155
Opened 2022-10-29 19:23 UTC by teoyuqi

Add some tests for code coverage purposes.

2022-10-30 03:36 UTC, cheeheng requested changes
LGTM except for some nitpicks

2022-10-30 03:36 UTC, cheeheng commented on src/test/java/seedu/address/model/util/SampleDataUtilTest.java
> +package seedu.address.model.util;
Is this worth the increase in test coverage (and amount of code written)? I feel that this file only adds to the overhead of testing while having little benefit to testing.

Essentially, this file is like a copy of `SampleDataUtil.java`. It would be difficult to find bugs because the code of these two files are essentially the same.

The effect is therefore, similar to duplicate code. If we want to change this in v1.5, then we will have to update two sources, which would be a waste of implementation time.

2022-10-30 03:36 UTC, cheeheng commented on src/test/java/seedu/address/model/module/ModuleTest.java
> +        assertEquals(expectedResult, MA2001.getModuleCodeAsUpperCaseString());
Perhaps you could test for a case where the module code in constructor is not in upper case, and add comments for that.

2022-10-30 03:36 UTC, cheeheng commented on src/test/java/seedu/address/logic/commands/DeletePersonFromModuleCommandTest.java
> +    public void execute_deletePersonFromModuleWhenModuleDoesNotExists_throwCommandException() {
Sorry for the minor nitpick. Grammatical error here?

```suggestion
    public void execute_deletePersonFromModuleWhenModuleDoesNotExist_throwCommandException() {
```

2022-10-30 08:45 UTC, teoyuqi commented on src/test/java/seedu/address/model/util/SampleDataUtilTest.java
> +package seedu.address.model.util;
This file actually increases the coverage a lot, since it was 0% coverage initially but is now 100% coverage 😅 
![image](https://user-images.githubusercontent.com/83915879/198870002-e888daf9-2b19-4ba4-b0d2-5613b8e69c58.png)

Am a little on the fence regarding this as well. On the one hand it is not exactly a meaningful test, but on the other hand, the 0% coverage dramatically lowers the coverage. @AY2223S1-CS2103T-T10-1/developers thoughts?

2022-10-30 08:46 UTC, teoyuqi commented on src/test/java/seedu/address/model/module/ModuleTest.java
> +        assertEquals(expectedResult, MA2001.getModuleCodeAsUpperCaseString());
Great idea!

2022-10-30 08:54 UTC, teoyuqi commented on src/test/java/seedu/address/logic/commands/DeletePersonFromModuleCommandTest.java
> +    public void execute_deletePersonFromModuleWhenModuleDoesNotExists_throwCommandException() {
Good catch!

2022-10-30 18:37 UTC, cheeheng reviewed
LGTM. Let's discuss whether the extra tests for the sample data file is really worth the reduction in bugs and increase in coverage.

2022-10-31 17:06 UTC, cheeheng approved these changes
LGTM

2022-11-01 13:58 UTC, Tan-Jia-Rong approved these changes
LGTM

2022-11-01 13:58 UTC, merged