Update user guide (features by @cheeheng)
AY2223S1-CS2103T-T10-1/tp pull request #159
Opened 2022-10-30 10:21 UTC by cheeheng

This user guide aims to update the sections corresponding to the following commands (incomplete)
- `add-module`
- `delete-module`
- `edit-module`
- `add-person-to-module` (pending @ekweirui's migration of `add-person-to-module` and `delete-person-from-module` to person section - rationale: to avoid merge conflict)

2022-10-30 12:05 UTC, ekweirui commented on docs/UserGuide.md
> +| **Module Code** | `m/` | Can only correspond to currently displayed module on screen (case-insensitive match) |
To be consistent with the constraints stated for module code in line 103, would it be more suitable to state that the same constraints over here, and bring 
` Can only correspond to currently displayed module on screen (case-insensitive match)` to a point form below?

2022-10-30 12:25 UTC, cheeheng commented on docs/UserGuide.md
> +[comment]: # (Inspiration behind the table obtained from https://ay2223s1-cs2103-f14-2.github.io/tp/UserGuide.html)
I don’t know, hence I just put it in.

2022-10-30 12:28 UTC, teoyuqi commented on docs/UserGuide.md
> +[comment]: # (Inspiration behind the table obtained from https://ay2223s1-cs2103-f14-2.github.io/tp/UserGuide.html)
I don't think it is necessary, since it is not a specific design that is unique to said team, but rather, just a means of data organization.

2022-10-30 12:28 UTC, cheeheng commented on docs/UserGuide.md
> +| **Module Code** | `m/` | Can only correspond to currently displayed module on screen (case-insensitive match) |
Good suggestion!

2022-10-30 14:46 UTC, cheeheng commented on docs/UserGuide.md
Good idea. Thanks.

2022-10-30 14:58 UTC, Tan-Jia-Rong reviewed
Just some minor nitpicks

2022-10-30 14:58 UTC, Tan-Jia-Rong commented on docs/UserGuide.md
> +* If provided module title is empty, then Plannit interprets it as that there is no module title.
```suggestion
* When the provided module title is empty, it will be interpreted as if there is no module title.
```

For clarity and sentence structure.

2022-10-30 14:58 UTC, Tan-Jia-Rong commented on docs/UserGuide.md
> +| **Module Title (Optional)** | `t/` | Can be any string of characters                         |
Should we put

**Module Code**

or follow our format input whereby we write **MODULE_CODE** instead

2022-10-30 14:58 UTC, Tan-Jia-Rong commented on docs/UserGuide.md
> +| **Module Code** | `m/` | Can only correspond to currently displayed module on screen (case-insensitive match) |
```suggestion
| **Module Code** | `m/` | Can only correspond to currently displayed module on screen (case-insensitive) |
```

I feel that it is sufficient to write (case-insensitive) without the match as idea is conveyed

Another suggestion:
```suggestion
| **Module Code** | `m/` | Must correspond to currently displayed module on screen (case-insensitive) |
```
Not asking for a change but I felt like writing must here sounds better. However, the implication is that it does match with the other constraints whereby it writes 
> Can only be non-empty string of alphanumeric characters

2022-10-30 15:01 UTC, ekweirui commented on docs/UserGuide.md
Great idea!

2022-10-30 15:01 UTC, Tan-Jia-Rong commented on docs/UserGuide.md
> +* If provided module title is empty, then Plannit interprets it as that there is no module title.
great mind think alike but I was 1 step late 😢

2022-10-30 15:04 UTC, cheeheng commented on docs/UserGuide.md
> +* If provided module title is empty, then Plannit interprets it as that there is no module title.
Thanks @Tan-Jia-Rong, but I decided to roughly follow @teoyuqi's suggestion because I feel that it is clearer that way.

2022-10-30 15:20 UTC, cheeheng commented on docs/UserGuide.md
> +| **Module Title (Optional)** | `t/` | Can be any string of characters                         |
I guess **Module Code** would be more human-readable? It should be clear enough even without the underscores and caps?

2022-10-30 18:44 UTC, teoyuqi requested changes

2022-10-30 18:44 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Module Code** | `m/` | Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul> |
```suggestion
| **Module Code** | `m/` |  {::nomarkdown}Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul>{:/} |
```
The ` {::nomarkdown}...{:/}` tags are needed for Github pages to display the html in tables correctly. Jekyll (specficially its Kramdown engine's) [issue](https://stackoverflow.com/a/57904161).

2022-10-30 18:44 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Module Code**  | `m/` | Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul>  |
```suggestion
| **Module Code**  | `m/` |  {::nomarkdown}Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul>{:/}  |
```

2022-10-31 14:26 UTC, Tan-Jia-Rong approved these changes
LGTM!

2022-10-31 14:26 UTC, merged