Add case-sensitivty constraints in flag table
AY2223S1-CS2103T-T10-1/tp pull request #170
Opened 2022-10-30 17:49 UTC by ekweirui

Currently, there is no mentioning of case-sensitivity in the user guide.

Thus this pull request aims to:
* add case-sensitivty constraints in flag table

2022-10-30 18:15 UTC, cheeheng submitted a review, later dismissed
LGTM

2022-10-30 18:41 UTC, teoyuqi requested changes

2022-10-30 18:41 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Name**  | `n/` | Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul> |
```suggestion
| **Name**  | `n/` | {::nomarkdown}Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul>{:/}  |
```
The ` {::nomarkdown}...{:/}` tags are needed for Github pages to display html in tables correctly.

2022-10-30 18:41 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Module Code** | `m/` | Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul> |
```suggestion
| **Module Code** | `m/` | {::nomarkdown}Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul>{:/} |
```

2022-10-30 18:41 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Name**        | `n/` | Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul> |
```suggestion
| **Name**        | `n/` |  {::nomarkdown}Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul>{:/} |
```

2022-10-30 18:41 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Name** | `n/` | Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul> |
```suggestion
| **Name** | `n/` |  {::nomarkdown}Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul>{:/} |
```

2022-10-30 18:41 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Module Code** | `m/` | Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul> |
```suggestion
| **Module Code** | `m/` |  {::nomarkdown}Module code <ul><li>is non-case sensitive</li> <li>can only be non-empty string of alphanumeric characters</li></ul>{:/} |
```

2022-10-30 18:41 UTC, teoyuqi commented on docs/UserGuide.md
> +| **Name**        | `n/` | Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul> |
```suggestion
| **Name**        | `n/` |  {::nomarkdown}Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul>{:/} |
```

2022-10-31 05:14 UTC, ekweirui commented on docs/UserGuide.md
> +| **Name**  | `n/` | Name <ul><li>is case sensitive</li> <li>can only be non-empty string of alphanumeric characters and spaces</li></ul> |
Thanks for noticing this!

2022-10-31 05:26 UTC, cheeheng approved these changes
LGTM

2022-10-31 08:25 UTC, teoyuqi approved these changes
LGTM

2022-10-31 08:25 UTC, merged