Update link documentation in User Guide and address link feature bugs
AY2223S1-CS2103T-T10-1/tp pull request #176
Opened 2022-11-01 12:30 UTC by shwene

This PR addresses the two issues #137 and #141 with changes to regex and feedback message. It also improves on the user guide (links). 
Opening of links from Plannit has been refactored such that it will be opened via Link class instead of 2 separate but duplicate methods in OpenLinkCommand.java and ModuleCard.java 

### Issue #141
It raises the functionality bug of the add-link feature whereby valid links are being incorrectly rejected. After several rounds of testing, a few more bugs related to link acceptance were uncovered.

1. Valid links with subdomains other than (www.) was being rejected. (e.g. 'open.kattis.com', and 'teams.microsoft.com')
2. Valid links with top level domains longer than 6 characters was being rejected (though less common, there are quite a few examples listed here: https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN)
3. Invalid links with symbols such as @ and \ within its domain name was being accepted. (e.g. email addresses)

#### New link regex requirements
##### Subdomain, Domain, and Top-Level Domain 
Only alphanumeric and hyphen characters can be included
Source:  www.rfc-editor.org/rfc/rfc3986 (only applies to English links, as there has been an update to domain names where other languages are valid also)

##### Remaining part of the URL (i.e. path/queries)
Printable ASCII characters (besides whitespace) are allowed. 
Rationale: Although there are conventions, organizations are free to decide on what characters to use. (Unlike the domain parts which are regulated).
Limitation: Non-ASCII characters (e.g. foreign language characters) are not considered due to parsing limitations of Plannit/Java/Json to store and open such characters.

### Issue #137
It raises the functionality bug add-link feature whereby the feedback message does not match the validation check being performed. As such, it has been updated to match the new link validation requirements.

### User Guide improvements

- Added user-centric explanation of and motivation behind link aliases (with example)
- Update constraints for link URLs in the relevant tables
- Included before and after images of add/delete link (excluded for open link as it is browser dependent)
- Reformatted table to ensure consistency of table formatting (as per @ekweirui 's suggestion)
- Updated command format explanation for `*` syntax (as per @cheeheng 's suggestion)

2022-11-02 08:04 UTC, teoyuqi requested changes
Some minor changes. Do remember to update screenshots with labels as well.

2022-11-02 08:04 UTC, teoyuqi commented on docs/UserGuide.md
> +| :bulb: **Tip:** Hover your cursor over aliases in Plannit to peak at their associated URL |
I believe you have to use the HTML format for the infoboxes in order for them to be displayed correctly:
```
<div markdown="span" class="alert alert-info"> :bulb: **Tip:**<br/>  
Hover your cursor over aliases in Plannit to peak at their associated URL.
</div>
```

2022-11-02 08:04 UTC, teoyuqi commented on docs/UserGuide.md
> +| :exclamation: **Alert:** Permissions from your operating system may be required for some users to open links from Plannit using either way<br>(They are enabled by default for most users) |
_see above comment_

2022-11-03 03:12 UTC, teoyuqi commented on docs/UserGuide.md
> +E.g., Using the alias `tut t10 v fun` to label the link `nus-sg.zoom.us/j/81374731875?pwd=ZE9hWFlNVGJVNENFQm1SREhVVEs5Zz09`
Maybe `Tutorial Zoom`?

2022-11-03 05:27 UTC, cheeheng requested changes
It looks like there is an important security issue here, where the password of a Zoom session is being leaked to the public.

2022-11-03 08:46 UTC, shwene commented on docs/UserGuide.md
> +| :bulb: **Tip:** Hover your cursor over aliases in Plannit to peak at their associated URL |
Thanks! Will apply to the others too

2022-11-03 08:47 UTC, shwene commented on docs/UserGuide.md
> +E.g., Using the alias `tut t10 v fun` to label the link `nus-sg.zoom.us/j/81374731875?pwd=ZE9hWFlNVGJVNENFQm1SREhVVEs5Zz09`
Ah, I wanted to showcase how aliases could be personalised

2022-11-04 02:17 UTC, cheeheng approved these changes
LGTM

2022-11-04 09:41 UTC, Tan-Jia-Rong approved these changes
LGTM

2022-11-04 10:26 UTC, teoyuqi approved these changes

2022-11-04 10:26 UTC, merged