Update `DeveloperGuide.md`
AY2223S1-CS2103T-T10-1/tp pull request #45
Opened 2022-09-22 07:17 UTC by teoyuqi

### The following changes were made:
1. Some of the preconditions for use cases ended with a period punctuation ("`.`") while others did not. A period was added  at the end of all preconditions for consistency.
2. There is a mix of the usage of "_displays_ error message" and "_shows_ error message". Occurrences of "shows" has been replaced with "displays" for consistency.
3. Under the extensions for the adding/deleting of tasks, the use case currently goes back to step 1 when the  extension ends. This is incorrect and has been corrected to "Use case ends".
4. Preconditions mentioning other use cases now include a hyperlink pointing towards the specific use case's heading.
5. Fix other minor typo errors and grammatical errors.

2022-09-22 07:23 UTC, cheeheng submitted a review, later dismissed
LGTM

2022-09-22 08:43 UTC, Tan-Jia-Rong requested changes
Just some minor nits, in addition to the empty lines after MSS, do check out the empty lines after Extensions too! Thank you! 😄

2022-09-22 08:43 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +    * 3b1. Plannit displays an error message.
When comparing to 3a1 and 3c1, it feels out of place without the notifying user that a duplicate exists

2022-09-22 08:43 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +      duplicate exists.
not sure but of that sounds slightly off
```suggestion
    * 3a1. Plannit displays an error message notifying user that a 
      duplicate exists.
```

2022-09-22 08:43 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
For standardisation, this blank line should be removed as well

2022-09-22 11:13 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +    * 3b1. Plannit displays an error message.
I have elaborated on the error message for 3b1, in line with that of 3a1 and 3c1 for commit [37040e9](https://github.com/AY2223S1-CS2103T-T10-1/tp/pull/45/commits/37040e9680a8412fdc2b206c4d3839df51329f6d).

2022-09-22 11:14 UTC, teoyuqi commented on docs/DeveloperGuide.md
Nice catch! I have removed the additional new line in commit [37040e9](https://github.com/AY2223S1-CS2103T-T10-1/tp/pull/45/commits/37040e9680a8412fdc2b206c4d3839df51329f6d).

2022-09-22 12:21 UTC, cheeheng approved these changes
LGTM

2022-09-24 15:22 UTC, Tan-Jia-Rong approved these changes
LGTM! Thanks for fixing the minor nits and improving on it 👍 😄

2022-09-24 15:22 UTC, merged