Update user guide (add/delete module)
AY2223S1-CS2103T-T10-1/tp pull request #47
Opened 2022-09-22 09:21 UTC by cheeheng

This pull request does the following:
1. Updates user guide for add/delete module section.
2. Fixes a few formatting inconsistencies and grammatical errors.

2022-09-22 11:35 UTC, teoyuqi requested changes
Just some minor clarifications to ensure consistency between our sections. Otherwise, LGTM.

2022-09-22 11:35 UTC, teoyuqi commented on docs/UserGuide.md
> +| `add module`      | `add    module   m/<MODULE_CODE> [t/<MODULE_TITLE>]`,<br>e.g.: `add module m/CS2103T t/Software Engineering`  |
```suggestion
| `add module`      | `add    module   m/MODULE_CODE [t/MODULE_TITLE]`,<br>e.g.: `add module m/CS2103T t/Software Engineering`  |
```

I think the `<>` is redundant now, since we have specified under `2. Features` (line 52) that words in `UPPER_CASE` are the parameters to be supplied by the user.

2022-09-22 11:35 UTC, teoyuqi commented on docs/UserGuide.md
> +Format: `add module m/<MODULE_CODE> [t/<MODULE_TITLE>]`
```suggestion
Format: `add module m/MODULE_CODE [t/MODULE_TITLE]`
```

2022-09-22 11:35 UTC, teoyuqi commented on docs/UserGuide.md
> +* `add module m/CS2103T` - adds a module CS2103T without a title
Would it be clearer to use a code block for each example, followed the explanation? (similar to what I did for tasks)

2022-09-22 11:35 UTC, teoyuqi commented on docs/UserGuide.md
> +Format: `delete module m/<MODULE_CODE>`
```suggestion
Format: `delete module m/MODULE_CODE`
```

2022-09-22 12:23 UTC, cheeheng commented on docs/UserGuide.md
> +| `add module`      | `add    module   m/<MODULE_CODE> [t/<MODULE_TITLE>]`,<br>e.g.: `add module m/CS2103T t/Software Engineering`  |
Good catch! Thanks so much for noticing that.

2022-09-22 18:16 UTC, ekweirui commented on docs/UserGuide.md
> +| `add module`      | `add    module   m/<MODULE_CODE> [t/<MODULE_TITLE>]`,<br>e.g.: `add module m/CS2103T t/Software Engineering`  |
Regarding this command summary table, would it be better if we replaced the column of `Format, Examples` with a short description? 

We could then make each command in the `Action` column "clickable", where clicking upon the command would bring the user to the respective command below.

2022-09-22 18:22 UTC, cheeheng commented on docs/UserGuide.md
> +Format: `add module m/<MODULE_CODE> [t/<MODULE_TITLE>]`
Thanks so much for that. I fixed it in my next commit.

2022-09-22 18:23 UTC, cheeheng commented on docs/UserGuide.md
> +* `add module m/CS2103T` - adds a module CS2103T without a title
I adopted your suggestion in the next commit, but removed the bullet point because it seems unnecessary, with only one point to convey.

2022-09-22 18:34 UTC, cheeheng commented on docs/UserGuide.md
> +| `add module`      | `add    module   m/<MODULE_CODE> [t/<MODULE_TITLE>]`,<br>e.g.: `add module m/CS2103T t/Software Engineering`  |
`Example` does not look necessary, but `Format` would be useful for quick reference. It looks like a good idea to make each action in the `Action` column clickable.

2022-09-22 18:35 UTC, ekweirui commented on docs/UserGuide.md
> +In this example, we are adding a module `CS2103T` which has the title `Software Engineering`.
Should this be "In the above example" instead, to standardize with the format in `add task` and `delete task`?

2022-09-22 20:22 UTC, ekweirui requested changes

2022-09-22 20:22 UTC, ekweirui commented on docs/UserGuide.md
> +| [`delete task`](#222-add-task)        | `delete task     m/MODULE_CODE n/TASK_NUMBER`      | Delete task corresponding to specified task number of specified module code |
Could the reference be wrong here? Also, the reference for `delete task` seems to be misplaced.
```suggestion
| [`add module`](#211-add-module-add-module)       | `add    module   m/MODULE_CODE [t/MODULE_TITLE]`   | Add module with a module code and optional module title                     |
| [`delete module`](#212-delete-module-delete-module) | `delete module   m/MODULE_CODE`                    | Delete module by module code                                                |
| [`add task`](#221-add-task-add-task)           | `add    task     m/MODULE_CODE d/TASK_DESCRIPTION` | Add task with specified module code and task description                    |
| [`delete task`](#222-delete-task-delete-task)        | `delete task     m/MODULE_CODE n/TASK_NUMBER`      | Delete task corresponding to specified task number of specified module code |
```
Should it be `#211-add-module-add-module` instead?

2022-09-23 05:10 UTC, cheeheng commented on docs/UserGuide.md
> +| [`delete task`](#222-add-task)        | `delete task     m/MODULE_CODE n/TASK_NUMBER`      | Delete task corresponding to specified task number of specified module code |
The reference for delete task is indeed misplaced. 

However, I have changed the headers accordingly (see line 71 after the change) because it is unnecessary to show "Add module: `add module`" when "Add module" is sufficient to drive the point across.

2022-09-23 05:13 UTC, cheeheng commented on docs/UserGuide.md
> +In this example, we are adding a module `CS2103T` which has the title `Software Engineering`.
Yes, you are right. Thank you so much for pointing that out.

2022-09-24 14:03 UTC, teoyuqi approved these changes
LGTM

2022-09-24 16:01 UTC, ekweirui approved these changes
Agree with your points, LGTM

2022-09-24 16:01 UTC, merged