Update user guide (add/delete contact)
AY2223S1-CS2103T-T10-1/tp pull request #49
Opened 2022-09-22 20:14 UTC by ekweirui

Currently, there are no details in the user guide that specifies how can users add and delete contacts.

Thus, this pull request aims to update user guide with details on addition and deletion of contacts.

In addition, this pull request fixes some formatting issues.

2022-09-23 04:00 UTC, cheeheng commented on docs/UserGuide.md
> +- `p/`: (Optional flag) To be followed by the email of the new contact.
Should this be phone number instead of email?

2022-09-23 14:33 UTC, ekweirui commented on docs/UserGuide.md
> +Expected outcome: The contact with name "Dinosaur Lim" and email "dinosaurlim@gmail.com" is added to Plannit.
Yes thanks for spotting the error 😄

2022-09-23 14:35 UTC, ekweirui commented on docs/UserGuide.md
> +- When adding a duplicate name, Plannit will override the old entry.
This is true, I have not yet cast either decision to stone. However, documentation should be consistent throughout all fronts. Thanks for pointing it out.

2022-09-23 14:36 UTC, ekweirui commented on docs/UserGuide.md
> +- `p/`: (Optional flag) To be followed by the email of the new contact.
After a discussion I had with @Tan-Jia-Rong in one of our previous meetings, I am leaning towards making email compulsory and phone number optional, differing from our draft User Guide.

2022-09-23 14:40 UTC, ekweirui commented on docs/UserGuide.md
> +- `p/`: (Optional flag) To be followed by the email of the new contact.
Yes you are right. Thanks for pointing it out.

2022-09-24 14:09 UTC, teoyuqi requested changes
Just a minor formatting issue. Otherwise all's good :)

2022-09-24 14:09 UTC, teoyuqi commented on docs/UserGuide.md
> +Examples:
Perhaps we could use a code block instead of inline code for the examples? I think it would be neater that way, and would also be consistent with me and Chee Heng's section.

i.e.:
Examples:
```
add contact n/Dinosaur Lim e/dinosaurlim@gmail.com
```

instead of 

Examples:
`add contact n/Dinosaur Lim e/dinosaurlim@gmail.com`

2022-09-24 16:12 UTC, ekweirui commented on docs/UserGuide.md
> +Examples:
Good point, will change it soon.

2022-09-25 14:40 UTC, teoyuqi approved these changes
LGTM

2022-09-25 17:10 UTC, Tan-Jia-Rong approved these changes
LGTM

2022-09-25 18:10 UTC, merged