Update user guide (navigation)
AY2223S1-CS2103T-T10-1/tp pull request #50
Opened 2022-09-23 07:09 UTC by Tan-Jia-Rong

Currently, there are no details in the user guide that specifies how should a user navigate between home page and modules in the program.

Thus, this pull request aims to update user guide with the details on navigating between home page and modules.

In addition, this pull request fixes some formatting issues.

2022-09-24 14:15 UTC, teoyuqi submitted a review, later dismissed
LGTM

2022-09-24 16:04 UTC, cheeheng requested changes
Apart from this change, this looks good to merge.

2022-09-24 16:04 UTC, cheeheng commented on docs/UserGuide.md
> +* In the above example, we are deleting task number **3** from the module
Should the bullet be removed (in the example section)? There is only one point per example, hence a bullet seems redundant. This would also make it consistent with my pull request.

2022-09-24 16:11 UTC, ekweirui commented on docs/UserGuide.md
> +* In the above example, we are deleting task number **3** from the module
This bullet point is present in @teoyuqi part, so it might be better if we kept it.
In addition regarding this issue, should we change the format to include expected outcome?
The proposed implementation would be something like:

In the example below, we are _______
```
Example 123
```
- The expected outcome is that ________

2022-09-24 17:09 UTC, cheeheng commented on docs/UserGuide.md
> +* In the above example, we are deleting task number **3** from the module
Regarding the bullet point issue, my pull request has been merged in, and this includes removing the bullet point in the Examples subsection. If you prefer keeping the bullet point, when you resolve the merge conflict, you should include the bullet point for the other parts for consistency.

For the expected outcome, it might be useful to describe where the output lies so that the user can interpret the output. However, I feel that this should not be the main priority for v1.1 because it involves getting the UI and implementation details clear. I believe that it would be better to update the expected outcome in the user guide as the feature gets implemented.

What about this as the format?
```
Example 123
```
* In the example above, we are ___
* The expected outcome is that ___

There will be fewer required changes, making it much easier to update the expected outcomes in the documentation as we code.

2022-09-26 10:57 UTC, Tan-Jia-Rong commented
Updated the format slightly in terms of line spacing before and after subtitle for consistency

2022-09-26 11:11 UTC, cheeheng requested changes

2022-09-26 11:11 UTC, cheeheng commented on docs/UserGuide.md
> +  {:toc}
Sorry for the nitpick. Did you mean to include that extra space here? If not, can you please remove it? Otherwise, it looks good to merge.

2022-09-26 11:23 UTC, Tan-Jia-Rong commented on docs/UserGuide.md
> +  {:toc}
No worries! Good to solve all mistakes if there are any 

The previous state was as follows
```
* Table of Contents
  {:toc}
```

I'll updated it to be as so
```
* Table of Contents
{:toc}
```

2022-09-26 11:25 UTC, ekweirui commented on docs/UserGuide.md
> +#### 2.5.1 Navigate to Home Page
Perhaps "Home Page" should be non-capitalized to be consistent with the others' headings?

2022-09-26 11:25 UTC, ekweirui commented on docs/UserGuide.md
> +* In the above example, we are navigating to the module with module code `CS2109S`.
Perhaps this should be a statement instead of a bulleted list to be consistent with the others?

2022-09-26 11:34 UTC, Tan-Jia-Rong commented on docs/UserGuide.md
> +#### 2.5.1 Navigate to Home Page
Alright found it looking weird initially when it is non caps (i.e home page || homepage)
Have since updated it to 
```
#### 2.5.1 Navigate to home
```

Same for modules as well

2022-09-26 13:07 UTC, ekweirui approved these changes
LGTM!

2022-09-27 01:34 UTC, cheeheng approved these changes
LGTM

2022-09-27 01:34 UTC, merged