Update user guide (add/delete link)
AY2223S1-CS2103T-T10-1/tp pull request #51
Opened 2022-09-24 16:49 UTC by shwene

Currently, there are no details in the user guide that specifies how users can add and delete links.

Thus, this pull request aims to update the user guide with details on addition and deletion of links.

2022-09-24 16:57 UTC, cheeheng requested changes

2022-09-24 16:57 UTC, cheeheng commented on docs/UserGuide.md
> +Format: `add link m/MODULE_CODE d/LINK_URL`
Should the command be `add link m/MODULE_CODE l/LINK_URL` instead? I saw this in line 184 (new index) as well.

2022-09-24 17:06 UTC, shwene commented on docs/UserGuide.md
> +Format: `add link m/MODULE_CODE d/LINK_URL`
Yup, will update

2022-09-24 17:11 UTC, cheeheng requested changes

2022-09-24 17:11 UTC, cheeheng commented on docs/UserGuide.md
> +* `l/`: This flag is to be followed immediately by the link url.
Should url be URL instead (to be consistent with what was written at lines 42-43 (new index))? Found this in line 182 (new index) as well. Sorry for minor nitpicking.

2022-09-24 17:17 UTC, shwene commented on docs/UserGuide.md
> +* `l/`: This flag is to be followed immediately by the link url.
Good catch, updated! (Better to nitpick now than in the future)

2022-09-25 14:36 UTC, ekweirui commented on docs/UserGuide.md
> +* The given link URL should not currently exist for the module in Plannit.
Perhaps mentioning what will happen if the user did so would be more informative?

For eg, When adding a duplicate link, Plannit displays an error message.

2022-09-25 14:36 UTC, ekweirui commented on docs/UserGuide.md
> +* The given link URL currently exists for the module in Plannit.
Same as above.

2022-09-26 09:53 UTC, cheeheng commented on docs/UserGuide.md
> +* The given link URL should not currently exist for the module in Plannit.
The bullet points below the format was originally supposed to state the preconditions rather than what you mentioned, but I now find that repetitive because the preconditions could be stated on top in the parameter specification instead.

A new section on the expected outcome like what @teoyuqi mentioned would help address this, but I believe we should not let this affect milestone v1.1 delivery. We are running late for this milestone because we were supposed to wrap the milestone up by 24 September (internal deadline) and now eating into the buffer delivery.

2022-09-26 10:25 UTC, cheeheng commented on docs/UserGuide.md
> +* The given link URL should not currently exist for the module in Plannit.
The bullet points below the format was originally supposed to state the preconditions rather than what you mentioned, but I now find that repetitive because the preconditions could be stated on top in the parameter specification instead.

A new section on the expected outcome like what @ekweirui mentioned would help address this. Mentioning what will happen if the user did something (including handling of exceptional cases) should go there.

I believe we should not let this affect milestone v1.1 delivery. We are running late for this milestone because we were supposed to wrap the milestone up by 24 September (internal deadline) and now eating into the buffer delivery.

2022-09-27 01:32 UTC, ekweirui approved these changes
LGTM!

2022-09-27 01:38 UTC, cheeheng approved these changes
LGTM

2022-09-27 01:38 UTC, merged