Implement add-link and delete-link command
AY2223S1-CS2103T-T10-1/tp pull request #65
Opened 2022-10-11 18:31 UTC by shwene

Currently, links cannot added to or removed from modules in Plannit.

Thus, this pull request does the following to incorporate links within modules in Plannit:

- Implement the add-link and delete-link commands for modules in Plannit
- Allow links to be launched from Plannit
- Add corresponding unit and integration tests
- Update user guide to include the newly added commands

Resolves #19 , #22.

2022-10-11 18:39 UTC, cheeheng commented on docs/UserGuide.md
> +| [`add-link`](#231-add-link)                         | `add    link     INDEX l/LINK_URL`                             | Add link URL to a module by its displayed index
Minor nitpicking here, but seems like you forgot to update hyphen here.

2022-10-12 03:08 UTC, shwene commented on docs/UserGuide.md
> +| [`add-link`](#231-add-link)                         | `add    link     INDEX l/LINK_URL`                             | Add link URL to a module by its displayed index
Thanks! Forgot to update when resolving the merge conflict

2022-10-12 10:02 UTC, teoyuqi requested changes
Just a few small changes here and there. Good job searching up on how to parse and open links in Java!

2022-10-12 10:27 UTC, Tan-Jia-Rong reviewed
LGTM aside from side typo found!

2022-10-12 10:27 UTC, Tan-Jia-Rong commented on src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
> +    public static final String MESSAGE_MISSING_LINK = "This link does not currently exist in module index ";
Can consider shifting to Messages for abstraction in v1.3

2022-10-12 10:27 UTC, Tan-Jia-Rong commented on src/main/java/seedu/address/model/Model.java
> +     * The module given in {@code editedPerson} must not be the same as another existing module in the address book.
```suggestion
     * The module given in {@code editedModule} must not be the same as another existing module in the address book.
```
Minor lapse in comment

2022-10-12 14:11 UTC, shwene commented on src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
> +    public static final String MESSAGE_MISSING_LINK = "This link does not currently exist in module index ";
Thanks! I have added square brackets around the index

2022-10-12 14:12 UTC, shwene commented on src/main/java/seedu/address/logic/parser/DeleteLinkCommandParser.java
> +        if (links.isEmpty() || (links.size() == 1 && links.contains(""))) {
Yup, just adjusted it according the suggestion

2022-10-12 14:13 UTC, shwene commented on src/test/java/seedu/address/logic/parser/AddLinkCommandParserTest.java
> +
The index that reaches addLinkCommand will be non negative and numeric as the parser using the Parser.parseIndex method, the testing of that is performed at StringUtilTest. Here the testing is on whether the index exists

2022-10-12 14:13 UTC, shwene commented on src/main/java/seedu/address/model/Model.java
> +     * The module given in {@code editedPerson} must not be the same as another existing module in the address book.
Thanks! Have adjusted accordingly

2022-10-12 15:18 UTC, ekweirui commented on src/main/java/seedu/address/model/link/Link.java
>  public class Link {
Currently, `Link` is in the model folder.
As links are tied to modules, I feel that we could consider moving this file to within `Module` itself, similar to `Task`.

2022-10-12 15:43 UTC, cheeheng approved these changes
Overall, LGTM, just some pointers to discuss for v1.3

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +
Perhaps for v1.3, you could test a link without https

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/logic/parser/AddLinkCommandParserTest.java
> +
Maybe we should reconsider for v1.3.

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/logic/parser/AddLinkCommandParserTest.java
> +    //Specific testing of link compatability performed at ParserUtilTest and LinkTest
Is the word `compatibility` misspelt in the comments?

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> +                + "https://nusmods.com") instanceof AddLinkCommand);
Perhaps the URL could be abstracted into a constant in `CommandTestUtil.java`?

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> +                + "https://nusmods.com") instanceof DeleteLinkCommand);
Same here

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/logic/parser/DeleteLinkCommandParserTest.java
> +    //Specific testing of link compatability performed at ParserUtilTest and LinkTest
Similar spelling mistake: compatability  ?

2022-10-12 15:43 UTC, cheeheng commented on src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
> +import static seedu.address.testutil.TypicalModules.GE3238;
Nice one here :)

2022-10-12 15:52 UTC, ekweirui commented on src/main/java/seedu/address/model/link/Link.java
>  public class Link {
Perhaps for future iterations, we could add an exception folder specific to links (like that of tasks/modules/persons) for consistency.

2022-10-12 16:08 UTC, Tan-Jia-Rong approved these changes
LGTM for v1.2. More improvements could be made moving forward for v1.3

2022-10-12 16:14 UTC, cheeheng commented on src/main/java/seedu/address/model/link/Link.java
>  public class Link {
When I implemented ModuleCode and ModuleTitle, I also put it outside of the Module class to be consistent with AB3. That is a good point @shwene.

2022-10-12 16:18 UTC, teoyuqi commented on src/main/java/seedu/address/storage/JsonAdaptedLink.java
> +public class JsonAdaptedLink {
Sorry that I missed this in my earlier review, but perhaps we could add unit testing for `JsonAdaptedLink` for future iterations.

2022-10-12 16:18 UTC, teoyuqi commented on src/main/java/seedu/address/storage/JsonAdaptedModule.java
> +        if (linked != null) {
Just noticed this as well. It appears that the `linked` argument can be null without any exceptions thrown. Does that mean that it will not detect errors in the data file? 

_i.e., if the data file was modified with the_ `linked` _field completely removed, instead of discarding the module, would it not notice the error and just create a module without links?_

2022-10-12 16:18 UTC, teoyuqi commented on src/main/java/seedu/address/logic/parser/DeleteLinkCommandParser.java
> +        if (isLinksEmpty || hasOnlyOneEmptyLink) {
Thank you for the change!

2022-10-12 16:21 UTC, teoyuqi approved these changes

2022-10-12 16:21 UTC, merged

2022-10-12 16:29 UTC, shwene commented on src/main/java/seedu/address/storage/JsonAdaptedModule.java
> +        if (linked != null) {
I followed the original implementation for Tag in Person where Link it initialized to an empty HashSet() at start as compared to the other fields where they are null at the start.

2022-10-12 16:30 UTC, cheeheng commented on src/main/java/seedu/address/storage/JsonAdaptedModule.java
> +        if (linked != null) {
It might result in an exception thrown in the Jackson library. Not only that, I am concerned that this would have led to more bugs which were hard to find.

2022-10-12 16:48 UTC, shwene commented on src/main/java/seedu/address/storage/JsonAdaptedModule.java
> +        if (linked != null) {
Given a data file (the json file) without the linked field, it will create a module without links. Then, when the user uses add-link on the module, the links field will be added into the json file.

2022-10-12 16:52 UTC, shwene commented on src/main/java/seedu/address/storage/JsonAdaptedModule.java
> +        if (linked != null) {
In terms of the background, the linked field in the module will be an empty Hashset<Link>