Update developer guide (add/delete/swap `Task`)
AY2223S1-CS2103T-T10-1/tp pull request #83
Opened 2022-10-17 12:17 UTC by teoyuqi

Updated developer guide for functionality of add, delete and swap task.

Also fixed a minor misnaming of variables in code committed earlier for `v1.2`.

2022-10-17 16:11 UTC, cheeheng requested changes
LGTM except for a few minor nitpicks.

2022-10-17 16:11 UTC, cheeheng commented on docs/diagrams/AddDeleteSwapTaskFeature/AddressBookObjectDiagram.puml
> +Module2 *--> "1" TaskList2 MODEL_COLOR_T5
Is there a reason why multiplicity is present in the object diagram?

2022-10-17 16:11 UTC, cheeheng commented on docs/diagrams/AddDeleteSwapTaskFeature/AddTaskSequenceDiagram.puml
> +@enduml
This sequence diagram might look a bit complicated but I feel that it couldn't be helped due to long method names. Let's discuss. This is not a request to change the sequence diagram.

2022-10-17 16:11 UTC, cheeheng commented on docs/DeveloperGuide.md
> +**Aspect: data structure to store `Task`:**
```suggestion
**Aspect: Data structure to store `Task`:**
```

Sorry for the minor nitpick, but could this capitalisation change be made so as to be consistent with line 270 (new index)?

2022-10-17 16:11 UTC, cheeheng commented on docs/diagrams/AddDeleteSwapTaskFeature/TaskListClassDiagram.puml
> +
Is there a reason why `Link` is left out? I feel that `Link` should be present due to completeness, or that `ModuleCode` and `ModuleTitle` attributes could be left out if the desire is to focus on primarily the `Task` and `TaskList`.

2022-10-18 13:40 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +application by inputting the `add-task` command followed by the `m/` flag to
```
We have implemented the following `Command` classes:
- `AddTaskCommand` allows the user to add a task to a specified `Module` in 
  **Plannit**.
- `DeleteTaskCommand` allows the user to delete a task from a specified 
  `Module` in **Plannit**.
- `SwapTaskCommand` allows the user to swap the order of `Task`s within a 
  specified `Module` in **Plannit**.
```
For consistency
```suggestion
Plannit by inputting the `add-task` command followed by the `m/` flag to 
```

2022-10-19 10:10 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +![AddTaskSequenceDiagram](images/AddDeleteSwapTaskFeature/AddTaskSequenceDiagram.png)
Require a note to indicate plantuml constraints

2022-10-19 13:46 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +a new `AddTaskComamandParser` is instantiated to parse the arguments.
Good catch, thank you! :)

2022-10-19 13:47 UTC, teoyuqi commented on docs/diagrams/AddDeleteSwapTaskFeature/AddressBookObjectDiagram.puml
> +Module2 *--> "1" TaskList2 MODEL_COLOR_T5
ooops ok I will remove it. Thank you for spotting it!

2022-10-19 14:11 UTC, ekweirui submitted a review, later dismissed
LGTM except for a minor nitpick.

2022-10-19 14:11 UTC, ekweirui commented on docs/DeveloperGuide.md
> +`AddTaskCommand` object that is returned to the `LogicManager`.
I feel that we can cut back on some details here, especially step 4. 

One guideline that I adopt when coming up with steps like these is to only include a step when I notice a need to include an object diagram to showcase a useful change after a particular scenario happened. 

For example in the scenario here, I would skimp past the details in step 3, 4 that are related to parsing, and focus on steps like 5, and 6 where I think object diagrams can be very helpful in helping to create a narrative here.

However, this is just a suggestion as this is just my personal style, but I do hope you find it useful~! 😄

2022-10-19 14:26 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +**Aspect: data structure to store `Task`:**
No worries! Thank you for pointing that out 😃

2022-10-19 14:39 UTC, teoyuqi commented on docs/diagrams/AddDeleteSwapTaskFeature/TaskListClassDiagram.puml
> +
Good catch, I will add `Link` into the diagram.

2022-10-19 14:40 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +![AddTaskSequenceDiagram](images/AddDeleteSwapTaskFeature/AddTaskSequenceDiagram.png)
Thank you for pointing out!

2022-10-19 15:19 UTC, Tan-Jia-Rong approved these changes
LGTM

2022-10-19 15:21 UTC, cheeheng approved these changes
LGTM

2022-10-19 15:21 UTC, merged