Update Developer Guide (Go to Module)
AY2223S1-CS2103T-T10-1/tp pull request #87
Opened 2022-10-18 14:57 UTC by Tan-Jia-Rong

Updated developer guide with regards to the functionality of go to module.

Included:
GoToCommand Sequence Diagram
GoToCommand Activity Diagram
Documentation on GoToCommand

2022-10-18 15:32 UTC, cheeheng requested changes
LGTM except for minor nitpicks

2022-10-18 15:32 UTC, cheeheng commented on docs/DeveloperGuide.md
> +a new `GoToComamandParser` is instantiated to parse the arguments.
```suggestion
a new `GoToCommandParser` is instantiated to parse the arguments.
```
Oops, looks like you repeated the same mistake as @teoyuqi. Did you mean `GoToCommandParser` instead?

2022-10-18 15:32 UTC, cheeheng commented on docs/DeveloperGuide.md
> +##### Reasons behind current choice:
```suggestion
##### Rationale behind current choice:
```
Sorry for starting this but could you change this part as follows? There is only one reason, which makes the plural form look weird.

2022-10-18 15:42 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +an `GoToCommand` object that is returned to the `LogicManager`.
yes there is thanks for spotting it!

2022-10-18 15:42 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +##### Reasons behind current choice:
Noted I shall implement the changes!

2022-10-18 15:44 UTC, Tan-Jia-Rong commented on docs/DeveloperGuide.md
> +a new `GoToComamandParser` is instantiated to parse the arguments.
yep that seems to be the case thanks for spotting this!

2022-10-18 16:23 UTC, cheeheng approved these changes
LGTM

2022-10-19 14:36 UTC, ekweirui approved these changes
LGTM

2022-10-19 14:48 UTC, teoyuqi approved these changes
LGTM, just a minor clarification on one part.

2022-10-19 14:48 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +**Step 9**: The home status is set to false via `ModelManager::SetHomeStatus`.
```suggestion
**Step 9**: The home status is set to `false` via `ModelManager::SetHomeStatus`.
```
Should this be a code snippet since it is a direct reference to a `boolean` primitive?

2022-10-19 14:48 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +##### Aspect: How find executes
```suggestion
##### Aspect: How `find` executes
```

Should this be a code snippet as well since we are referring to the command here?

2022-10-19 14:48 UTC, teoyuqi commented on docs/DeveloperGuide.md
> +    * Cons: Require user to navigate back to home page before going to another module which might be unintuitive for users.
```suggestion
    * Cons: Require users to navigate back to home page before going to another module which might be unintuitive for users.
```

2022-10-19 14:48 UTC, merged