Add test cases for `PersonIsInModulePredicate`
AY2223S1-CS2103T-T10-1/tp pull request #93
Opened 2022-10-21 18:22 UTC by ekweirui

Currently there exists no test cases for `PersonIsInModulePredicate`.

Thus, this pull request aims to 
* Add test cases for `PersonIsInModulePredicate`

2022-10-22 05:36 UTC, cheeheng submitted a review, later dismissed

2022-10-22 05:36 UTC, cheeheng commented on src/main/java/seedu/address/model/module/Module.java
>          requireAllNonNull(moduleCode, moduleTitle, tasks, links);
Here, perhaps calling `this(moduleCode, moduleTitle, tasks, links, new HashSet<>())` would reduce duplication of code.

2022-10-22 05:36 UTC, cheeheng commented on src/main/java/seedu/address/model/module/Module.java
>          requireAllNonNull(moduleCode, moduleTitle, links);
same here

2022-10-22 05:38 UTC, cheeheng requested changes
LGTM except for minor nitpicks on code duplication.

2022-10-22 07:09 UTC, teoyuqi commented on src/main/java/seedu/address/model/module/Module.java
>          requireAllNonNull(moduleCode, moduleTitle, tasks, links);
@cheeheng @ekweirui Might it be better to just completely remove the constructor without `persons`, as is in [my PR](https://github.com/AY2223S1-CS2103T-T10-1/tp/pull/90/files#diff-b54a161a8ba7b8350ffbd0a481fc7d3aced24bba452d1b46621499acddea5115)? 

I can't seem to think of any cases whereby we would need the constructor without `persons`. My concern is that leaving it in might introduce bugs, e.g.:
Suppose we already have a set of `Person` to instantiate a `Module` with, but we forget to include it in the  constructor. The constructor without the `persons` argument is called without any bugs. On the other hand, by removing the constructor without the `persons` argument, Java would notice the missing argument and throw an exception.

2022-10-22 07:11 UTC, teoyuqi commented on src/main/java/seedu/address/model/module/Module.java
>          requireAllNonNull(moduleCode, moduleTitle, tasks, links);
The only concern would be the need to update past code and tests to work using the new constructor. However, I have updated them to use the constructor with `persons` in my PR already.

2022-10-23 05:17 UTC, ekweirui commented on src/main/java/seedu/address/model/module/Module.java
>          requireAllNonNull(moduleCode, moduleTitle, tasks, links);
Adopted the `this(...)` approach to reduce duplication of code.

2022-10-23 05:41 UTC, cheeheng submitted a review, later dismissed
LGTM

2022-10-25 10:39 UTC, teoyuqi commented on src/main/java/seedu/address/model/module/Module.java
>      private final Set<Link> links = new HashSet<>();
```suggestion
    private final Set<Link> links;
```
Hmm was there an error in resolving the merge conflict? I believe it was previously agreed that `links`, `persons`  and `tasks` will all be initialised as `null`.

2022-10-25 18:43 UTC, teoyuqi approved these changes
LGTM!

2022-10-26 05:55 UTC, Tan-Jia-Rong approved these changes
LGTM

2022-10-26 05:55 UTC, merged